name: 04-using-actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults property sets default configs at the job level
    # good for configs that is shared among steps under the same job
    defaults:
      run:
        working-directory: react-app
    steps:
      # 1. Checkout code from repository
      - name: Checkout Code
        uses: actions/checkout@v4
      # 2. Setup node js with version 20 or above
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # 3. Install dependencies; Run the command in the working directory called react-app
      - name: Install dependencies
        run: npm install
      # 4. Build react app
      - name: Build react app
        run: npm run build

          
          
