name: 06-contexts
on:
  push:
  workflow_dispatch:
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          "Event name: ${{ github.event_name }}"
          "Ref: ${{ github.ref }}"
          "SHA: ${{ github.sha }}"
          "Actor: ${{ github.actor }}"
          "Workflow: ${{ github.workflow }}"
          "Run ID: ${{ github.run_id }}"
          "Run Number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: |
          "${{ vars.MY_VAR }}"
  