name: 07-using-expressions
run-name: "07 - Using expressions | DEBUG - ${{ inputs.debug == true && 'on' || 'off' }} "
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[${{ inputs.debug }}] Print start-up data"
        # Execute the run command if debug variable is set to true
        if: inputs.debug == true
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch ${{ github.ref }}"
          echo "Commit SHA ${{ github.sha }}"
          echo "Runner OS ${{ runner.os }}"
      - name: "[${{ inputs.debug }}] Print when triggered from main"
        # Execute the run command if debug variable is set to true
        # and triggered from main branch
        if: inputs.debug == true && github.ref_name == 'main'
        run: |
          echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"



